# Generated by Django 2.2.4 on 2019-10-25 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nutrition_grades', models.CharField(max_length=1)),
                ('ingredients', models.TextField()),
                ('url', models.CharField(max_length=400)),
                ('image_url', models.CharField(max_length=400)),
                ('nutrional_url', models.CharField(max_length=400)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
                ('user', models.ManyToManyField(related_name='product_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
